host: 0.0.0.0 # optional
rpcPort: 26657 # optional
lcdPort: 1317 # optional
grpcPort: 9090 # optional

node: # optional, defaults to values below
  host: 127.0.0.1 # optional
  rpcPort: 26657 # optional
  lcdPort: 1317 # optional
  grpcPort: 9090 # optional

cache: # optional, defaults to values below
  ttl: 5s # optional
  touchOnHit: false # optional

metrics: # optional, defaults to values below
  enable: true # optional
  port: 9001 # optional

lcd: # optional, defaults to allow everything
  default: allow # optional

  rules: # default is empty
    - priority: 9999 # optional, defaults to 1000
      action: deny # either allow or deny
      paths: [ ] # empty or nil means all
      methods: [ ] # empty or nil means all
      cache: # empty or nil means disabled
        enable: false
        ttl: 10s # optional, defaults to global .cache.ttl (5s if not specified)

    - priority: 1000
      action: allow
      paths:
        - /cosmos/staking/v1beta1/params
      methods:
        - GET
      cache:
        enable: true
        ttl: 20s

    - priority: 1000
      action: allow
      paths:
        - /cosmos/staking/v1beta1/validators
        - /cosmos/staking/v1beta1/pool
        - /cosmos/distribution/v1beta1/community_pool
        - /cosmos/base/tendermint/v1beta1/node_info
        - /cosmos/bank/v1beta1/supply/by_denom
        - /cosmos/mint/v1beta1/inflation
        - /cosmos/bank/v1beta1/supply/*
        - /cosmos/base/tendermint/v1beta1/validatorsets/*
        - /cosmos/base/tendermint/v1beta1/blocks/*
      methods:
        - GET
      cache:
        enable: true

grpc: # optional, defaults to allow everything
  default: allow # optional

  rules: # default is empty
    - action: allow
      methods: # empty or nil means all
        - /cosmos.bank.v1beta1.Query/AllBalances

rpc: # optional, defaults to allow everything
  default: allow # optional

  rules: # default is empty
    - priority: 9999 # optional, defaults to 1000
      action: deny # either allow or deny
      paths: [ ] # empty or nil means all
      methods: [ ] # empty or nil means all
      cache: # empty or nil means disabled
        enable: false
        ttl: 10s # optional, defaults to global .cache.ttl (5s if not specified)

    - action: allow
      paths:
        - /status
      methods:
        - GET
      cache:
        enable: true
        ttl: 2s

  jsonrpc: # optional, default is allow everything
    default: allow

    webSocketEnabled: true # optional, enabled by default
    webSocketConnections: 10 # optional

    rules: # default is empty
      - priority: 9999 # optional, defaults to 1000
        action: deny # either allow or deny
        methods: [ ] # empty or nil means all
        params: {} # empty or nil means all
        cache: # empty or nil means disabled
          enable: false
          ttl: 10s # optional, defaults to global .cache.ttl (5s if not specified)

      - action: allow
        methods: [ "subscribe", "unsubscribe", "unsubscribe_all" ]

      - action: allow
        methods: [ "status" ]
        cache:
          enable: true

      - action: allow
        methods: [ "abci_query" ]
        params:
          path: /cosmos.bank.v1beta1.Query/AllBalances
        cache:
          enable: true
          ttl: 2s

      - action: allow
        methods: [ "abci_query" ]
        params:
          path: /nibiru.epochs.v1.Query/EpochInfos

      - action: allow
        methods: [ "abci_query" ]
        params:
          path: /cosmos.distribution.v1beta1.Query/DelegationTotalRewards
