node:
  host: 10.0.28.28

cache:
  ttl: 5s

lcd:
  rules:
    - priority: 9999
      action: deny
      paths: [ ]
      methods: [ ]

    - priority: 1000
      action: allow
      paths:
        - /cosmos/staking/v1beta1/params
      methods:
        - GET
      cache:
        enable: true
        ttl: 20s

    - priority: 1000
      action: allow
      paths:
        - /cosmos/staking/v1beta1/validators
        - /cosmos/staking/v1beta1/pool
        - /cosmos/distribution/v1beta1/community_pool
        - /cosmos/base/tendermint/v1beta1/node_info
        - /cosmos/bank/v1beta1/supply/by_denom
        - /cosmos/mint/v1beta1/inflation
        - /cosmos/bank/v1beta1/supply/*
        - /cosmos/base/tendermint/v1beta1/validatorsets/*
        - /cosmos/base/tendermint/v1beta1/blocks/*
      methods:
        - GET
      cache:
        enable: true

grpc:
  rules:
    - action: allow
      methods:
        - /cosmos.bank.v1beta1.Query/AllBalances

rpc:
  rules:
    - priority: 9999
      action: deny
      path: [ ]
      methods: [ ]

    - action: allow
      paths:
        - /status
      methods:
        - GET
      cache:
        enable: true
        ttl: 2s

  jsonrpc:
    rules:
      - priority: 9999
        action: deny
        methods: [ ]

      - priority:
        action: allow
        methods: [ "status" ]
        cache:
          enable: true

      - priority:
        action: allow
        methods: [ "abci_query" ]
        params:
          path: /cosmos.bank.v1beta1.Query/AllBalances
        cache:
          enable: true
          ttl: 2s

      - priority:
        action: allow
        methods: [ "abci_query" ]
        params:
          path: /nibiru.epochs.v1.Query/EpochInfos

      - priority:
        action: allow
        methods: [ "abci_query" ]
        params:
          path: /cosmos.distribution.v1beta1.Query/DelegationTotalRewards
